// Icosphere geometry for the Earth's two LOD layers (see earth.ts):
//   - a coarse, always-resident full sphere (level ~6-7) that covers
//     everything, inset slightly below the true radius so detail chunks
//     (drawn at/above the true radius) are never z-fought by it;
//   - high-detail chunks (level 8-9, ~4096 tri each) streamed in on demand
//     for whatever is within ~horizon distance of the sub-station point,
//     keyed by a fixed level-3 seed grid (1280 seeds) so "which chunk is
//     this" is a stable index across frames.
//
// A chunk is generated by taking a barycentric grid over a single triangle
// (i along corner0->corner1, j along corner0->corner2, i+j<=n) and
// normalizing each grid point back onto the unit sphere.
//
// Every geometry produced here carries a per-vertex `aSkirt` value (0 or 1):
// the vertex shader skips heightmap displacement entirely where aSkirt=1, so
// the *same* shader serves the flat, undisplaced coarse sphere (aSkirt=1
// everywhere) and detail chunks' skirt curtains (aSkirt=1 on the border ring
// only, dropped a few km below the surface at build time to paper over
// cracks between chunks of different tessellation).

export interface BuiltMesh {
  positions: Float32Array; // xyz per vertex, already scaled to the base radius (km)
  aSkirt: Float32Array; // 0 = displace with the heightmap, 1 = don't (flat)
  indices: Uint16Array | Uint32Array;
}

export interface SeedChunk {
  index: number;
  corners: [Vec, Vec, Vec];
  /** Unit-vector centroid, used for LOD distance tests. */
  center: Vec;
}

type Vec = [number, number, number];

function normalize(v: Vec): Vec {
  const len = Math.hypot(v[0], v[1], v[2]) || 1;
  return [v[0] / len, v[1] / len, v[2] / len];
}

function add3(a: Vec, b: Vec): Vec {
  return [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
}

interface Grid {
  corners: Vec[][];
  rowStart: number[];
  n: number;
}

/** Triangular barycentric grid over (v0,v1,v2): i along v0->v1, j along v0->v2, i+j<=n. */
function triangleGrid(v0: Vec, v1: Vec, v2: Vec, n: number): Grid {
  const rowStart: number[] = new Array(n + 2);
  let acc = 0;
  for (let i = 0; i <= n + 1; i++) {
    rowStart[i] = acc;
    acc += n + 1 - i;
  }
  const corners: Vec[][] = [];

  for (let i = 0; i <= n; i++) {
    const row: Vec[] = [];
    for (let j = 0; j <= n - i; j++) {
      const iu = i / n;
      const ju = j / n;
      const x = v0[0] + (v1[0] - v0[0]) * iu + (v2[0] - v0[0]) * ju;
      const y = v0[1] + (v1[1] - v0[1]) * iu + (v2[1] - v0[1]) * ju;
      const z = v0[2] + (v1[2] - v0[2]) * iu + (v2[2] - v0[2]) * ju;
      row.push(normalize([x, y, z]));
    }
    corners.push(row);
  }

  return { corners, rowStart, n };
}

const T = (1 + Math.sqrt(5)) / 2;
const BASE_VERTS: Vec[] = (
  [
    [-1, T, 0], [1, T, 0], [-1, -T, 0], [1, -T, 0],
    [0, -1, T], [0, 1, T], [0, -1, -T], [0, 1, -T],
    [T, 0, -1], [T, 0, 1], [-T, 0, -1], [-T, 0, 1],
  ] as Vec[]
).map(normalize);

const BASE_FACES: [number, number, number][] = [
  [0, 11, 5], [0, 5, 1], [0, 1, 7], [0, 7, 10], [0, 10, 11],
  [1, 5, 9], [5, 11, 4], [11, 10, 2], [10, 7, 6], [7, 1, 8],
  [3, 9, 4], [3, 4, 2], [3, 2, 6], [3, 6, 8], [3, 8, 9],
  [4, 9, 5], [2, 4, 11], [6, 2, 10], [8, 6, 7], [9, 8, 1],
];

/** All seed chunks at a given icosahedron subdivision level (20 * 4^level of them). */
export function buildSeedChunks(level: number): SeedChunk[] {
  const n = 2 ** level;
  const seeds: SeedChunk[] = [];
  for (const [a, b, c] of BASE_FACES) {
    const grid = triangleGrid(BASE_VERTS[a], BASE_VERTS[b], BASE_VERTS[c], n);
    for (let i = 0; i < n; i++) {
      const rowLen = n - i;
      for (let j = 0; j < rowLen; j++) {
        const v0 = grid.corners[i][j];
        const v1 = grid.corners[i + 1][j];
        const v2 = grid.corners[i][j + 1];
        seeds.push({ index: seeds.length, corners: [v0, v1, v2], center: normalize(add3(add3(v0, v1), v2)) });
        if (j < rowLen - 1) {
          const w0 = grid.corners[i + 1][j];
          const w1 = grid.corners[i + 1][j + 1];
          const w2 = grid.corners[i][j + 1];
          seeds.push({ index: seeds.length, corners: [w0, w1, w2], center: normalize(add3(add3(w0, w1), w2)) });
        }
      }
    }
  }
  return seeds;
}

/** Builds one seed's fine mesh at `extraLevels` further subdivisions
 * (4^extraLevels triangles), at `radiusKm`. With `skirtDropKm > 0`, adds a
 * drop-curtain of triangles around the three border edges (aSkirt=1, no
 * heightmap displacement) to hide seams against neighboring/coarser meshes. */
export function buildChunkMesh(seed: SeedChunk, extraLevels: number, radiusKm: number, skirtDropKm: number): BuiltMesh {
  const n = 2 ** extraLevels;
  const grid = triangleGrid(seed.corners[0], seed.corners[1], seed.corners[2], n);
  const rowStart = grid.rowStart;
  const idx = (i: number, j: number) => rowStart[i] + j;
  const mainVertCount = rowStart[n + 1];

  const border = skirtDropKm > 0;
  // Border vertex indices, in order, for each of the 3 edges (i=0; j=0; i+j=n).
  const edgeA: number[] = []; // i=0, j=0..n
  const edgeB: number[] = []; // j=0, i=0..n
  const edgeC: number[] = []; // i+j=n, i=0..n
  if (border) {
    for (let j = 0; j <= n; j++) edgeA.push(idx(0, j));
    for (let i = 0; i <= n; i++) edgeB.push(idx(i, 0));
    for (let i = 0; i <= n; i++) edgeC.push(idx(i, n - i));
  }
  const skirtEdges = border ? [edgeA, edgeB, edgeC] : [];
  const skirtVertCount = skirtEdges.reduce((s, e) => s + e.length, 0);
  const totalVertCount = mainVertCount + skirtVertCount;

  const positions = new Float32Array(totalVertCount * 3);
  const aSkirt = new Float32Array(totalVertCount);

  for (let i = 0; i <= n; i++) {
    for (let j = 0; j <= n - i; j++) {
      const p = grid.corners[i][j];
      const vi = idx(i, j);
      positions[vi * 3 + 0] = p[0] * radiusKm;
      positions[vi * 3 + 1] = p[1] * radiusKm;
      positions[vi * 3 + 2] = p[2] * radiusKm;
    }
  }

  const triCount = n * n;
  const skirtTriCount = border ? skirtEdges.reduce((s, e) => s + (e.length - 1) * 2, 0) : 0;
  const indices = new Uint16Array((triCount + skirtTriCount) * 3);
  let w = 0;
  for (let i = 0; i < n; i++) {
    const rowLen = n - i;
    for (let j = 0; j < rowLen; j++) {
      const a = idx(i, j);
      const b = idx(i + 1, j);
      const c = idx(i, j + 1);
      indices[w++] = a;
      indices[w++] = b;
      indices[w++] = c;
      if (j < rowLen - 1) {
        const d = idx(i + 1, j + 1);
        indices[w++] = b;
        indices[w++] = d;
        indices[w++] = c;
      }
    }
  }

  if (border) {
    const skirtR = radiusKm - skirtDropKm;
    let sv = mainVertCount;
    for (const edge of skirtEdges) {
      const skirtStart = sv;
      for (const srcIdx of edge) {
        positions[sv * 3 + 0] = (positions[srcIdx * 3 + 0] / radiusKm) * skirtR;
        positions[sv * 3 + 1] = (positions[srcIdx * 3 + 1] / radiusKm) * skirtR;
        positions[sv * 3 + 2] = (positions[srcIdx * 3 + 2] / radiusKm) * skirtR;
        aSkirt[sv] = 1;
        sv++;
      }
      for (let k = 0; k < edge.length - 1; k++) {
        const s0 = edge[k];
        const s1 = edge[k + 1];
        const t0 = skirtStart + k;
        const t1 = skirtStart + k + 1;
        indices[w++] = s0;
        indices[w++] = t0;
        indices[w++] = t1;
        indices[w++] = s0;
        indices[w++] = t1;
        indices[w++] = s1;
      }
    }
  }

  return { positions, aSkirt, indices };
}

/** Merges many seeds' coarse (flat, undisplaced) meshes into one big
 * BuiltMesh for a single draw call -- used for the always-resident base
 * sphere. No skirts (it has no neighbors to seam against; detail chunks
 * simply draw over it). */
export function buildMergedCoarseSphere(seeds: SeedChunk[], extraLevels: number, radiusKm: number): BuiltMesh {
  const n = 2 ** extraLevels;
  const vertsPerSeed = ((n + 1) * (n + 2)) / 2;
  const trisPerSeed = n * n;

  const totalVerts = seeds.length * vertsPerSeed;
  const positions = new Float32Array(totalVerts * 3);
  const aSkirt = new Float32Array(totalVerts).fill(1);
  const indices = totalVerts > 65535 ? new Uint32Array(seeds.length * trisPerSeed * 3) : new Uint16Array(seeds.length * trisPerSeed * 3);

  let pw = 0;
  let iw = 0;
  for (const seed of seeds) {
    const mesh = buildChunkMesh(seed, extraLevels, radiusKm, 0);
    const base = pw / 3;
    positions.set(mesh.positions, pw);
    pw += mesh.positions.length;
    for (let k = 0; k < mesh.indices.length; k++) indices[iw++] = mesh.indices[k] + base;
  }

  return { positions, aSkirt, indices };
}
